### ISSUE TITLE
Where is the source code for generating bincode file?

### ISSUE THREAD

**Issue by gembin** [cgburgess/badge-maker#11]
Where is the source code for generating bincode file ?
https://github.com/cgburgess/badge-maker/tree/master/fonts

Thanks!

**Comment by cgbur** [comment]
I believe that comes from the JavaScript version of badge maker. If you look at their source I think they have a repository for it. If I ever get around to working on this seriously again I will be working on a badgen version which I don’t think uses the fonts and is much better.
